### ISSUE TITLE
Cannot open a folder inside a folder inside a pbo

### ISSUE THREAD

**Issue by EL-D148L0** [dedmen/PboExplorer#3]
if you open any pbo that contains a folder inside a folder and try to navigate to the second folder, the contents of the root folder will be displayed.

i've attached a barebones addon that demonstrates this behaviour.
[test.zip](https://github.com/dedmen/PboExplorer/files/12521196/test.zip)
![image](https://github.com/dedmen/PboExplorer/assets/76044636/0187ac87-cba5-4d91-b6eb-9dfd88ca214d)

**Comment by dedmen** [comment]
Fixed with todays release. 
This was a fun one
